### ISSUE TITLE
How to use my own dataset to test?

### ISSUE THREAD

**Issue by gwxxx** [VITA-Group/FSGS#11]

**Comment by zehaozhu** [comment]
Hi, thanks for your interest in our work.

You should modify [this script](https://github.com/VITA-Group/FSGS/blob/main/tools/colmap_llff.py) to preprocess your own data to get the camera poses and fused point cloud. Please note that [this script](https://github.com/VITA-Group/FSGS/blob/main/tools/colmap_llff.py) assumes the dataset have known camera poses, therefore in your own dataset you should utilize colmap to predict the camera poses first.
