### ISSUE TITLE
Sparse or Dense Point Clouds as Input

### ISSUE THREAD

**Issue by fanyang3** [VITA-Group/FSGS#13]
Nice work！But I have a question about this work. I noticed that you used COLMAP to do both sparse and dense reconstruction. May I ask if you are using sparse or dense point clouds as input for 3D Gaussian Splatting?
Looking forward to your reply！
![微信图片_20231213152334](https://github.com/VITA-Group/FSGS/assets/93926772/2465c918-3970-4797-941a-4fc7b14f7ae9)

**Comment by zehaozhu** [comment]
Hi, we use dense point clouds as inputs

**Comment by leo-frank** [comment]
How to use sparse point clouds as inputs?

**Comment by leo-frank** [comment]
BTW, is it reasonable to use dense point clouds under sparse setting ? 

I think that the final rendering quality has relation with initial points, so it may be not reasonable.

**Comment by zehaozhu** [comment]
Hi @leo-frank 

Thanks for your interest in our work.

The initial number of point cloud does affect rendering quality.

The sparse setting focus on NVS from sparse input views and the dense point cloud only comes from  sparse input views. So I think it's reasonalbe to use dense points as long as long as it does not introduce any additional information beyond what is already provided by the sparse views.
