### ISSUE TITLE
Quality issues

### ISSUE THREAD

**Issue by MrNeRF** [VITA-Group/FSGS#14]
Hi, 
thank you for your code and the paper.
I got it running although it has some bugs where it crashed. I can upstream the fixes later today.
Unfortunately, the quality of the output is very bad. Not sure if there are more substantial bugs in the code. I have been running it following your instructions.

Thank you.
MrNeRF

![Screenshot from 2023-12-13 11-20-24](https://github.com/VITA-Group/FSGS/assets/33876434/ef19fd9e-b315-40a2-80d4-c687efca0857)
![Screenshot from 2023-12-13 11-16-32](https://github.com/VITA-Group/FSGS/assets/33876434/f9cf174b-db74-4997-a346-5545beef8e69)

**Comment by zehaozhu** [comment]
Hi, thanks for your interest in our work. What is your PSNR and LPIPS for this scene?

**Comment by zehaozhu** [comment]
Actually, we are still tuning settinigs on MiP-NeRF 360 dataset. We plan to release the updated version either this week or the next.

**Comment by MrNeRF** [comment]
Ok, great. I did not run it again as it takes quite long. So I don't remember theses measures.  But overall the rendering output was low quality. I will rerun it when you update the code and report the measures. I am curious how it turns out.

**Comment by dlazares** [comment]
@zehaozhu 
I ran this on the bonsai scene and PSNR rises to 29 by 2k iters and then drops to 20 after iteration 2000 when the pseudo depth kicks in. visually I'm seeing similar artifacts to what's happening in MrNeRFs

**Comment by zehaozhu** [comment]
Hi @MrNeRF @dlazares 

The issue arises from the high weight of the pseudo depth loss applied after 2000 iterations. You can try the new version of code and use the [commands](https://github.com/VITA-Group/FSGS#training) for training  (need to recompile the simple-knn submodule) 

Thank you.
Zehao
