### ISSUE TITLE
FileNotFoundError: No such file or directory: '../sparse/0/images.txt'

### ISSUE THREAD

**Issue by ZhangCYG** [VITA-Group/FSGS#15]
In COLMAP process, I found that file '../sparse/0/images.txt' is read, but in current released LLFF and MIP360 datasets, all provided files are in format of bin, like  '../sparse/0/images.bin'. I wonder how I can get txt files in order to run the COLMAP process?

**Comment by ZhangCYG** [comment]
I find that the there's a problem of COLMAP installing on my machine. hh

**Comment by CrescentRosexx** [comment]
所以这个问题是咋解决的呀，大佬

> Refere

**Comment by CrescentRosexx** [comment]
所以这个问题是咋解决的呀，大佬

**Comment by lovejoker1102** [comment]
我也遇到了这个问题，是如何解决的，大佬

**Comment by renaissanceee** [comment]
the same problem, since only .bin file in 360v2 dataset. Anyone find solution?

**Comment by MickShen7558** [comment]
You might want to check the installation of your colmap by:
`colmap help`
in the terminal.

**Comment by ayatemp** [comment]
I have the same problem. So Could you explain how to fix this problem?
Now I'm trying to change bin file into txt file, but I couldn't use this txt file because the bin file was not valid to change txt file.

**Comment by Sibo2rr** [comment]
use colmap model_converter  --input_path ./dataset/mipnerf360/bicycle/sparse/0/ --output_path .dataset/mipnerf360/bicycle/sparse/0/  --output_type TXT in command line first to get txt files
