### ISSUE TITLE
Question about the rasterization

### ISSUE THREAD

**Issue by zhanglk9** [VITA-Group/FSGS#16]
Thanks for your great works!!
I notices that you have computed the gradient of `weight`,which is value of  `T*alpha`   when running the backward::renderCUDA(maybe at line 567 in `backward.cu` ).
I just want to know why add this gradient . Because in the gaussian-splatting's code ,this is not added.

**Comment by zehaozhu** [comment]
Hi @zhanglk9 

Thanks for your interest in our work. This gradient is based on the formulation `C_out = α * C_src + (1 - α) * C_dst`  for alpha compositing
