### ISSUE TITLE
Blender dataset processing

### ISSUE THREAD

**Issue by jiaw-z** [VITA-Group/FSGS#19]
Hello, thank you for sharing this excellent work. I wonder if there is any plan to release the code related to Blender dataset processing?

**Comment by zehaozhu** [comment]
Hi, thanks for you interest in our work. We have no plan to release the pre-processing code of Blender dataset but it is very similar to what we have done in MipNerf360 dataset.

**Comment by lovejoker1102** [comment]
I have the same problem, too
