### ISSUE TITLE
argument "train_bg"

### ISSUE THREAD

**Issue by weijielyu** [VITA-Group/FSGS#20]
Thank you for this great work! I noticed there's an argument "train_bg" in train.py that wasn't used. Out of curiosity, is there any case where optimizing background would be useful? Thank you!

**Comment by zehaozhu** [comment]
Hi, thanks for your interest in our work.

When adding train_bg argument, we will generate a learnable parameter to represent the background, with dimension of 3. 

In my own case, adding train_bg will not lead to any improvement and the bg parameter will be either [0,0,0] or [1,1,1], almost equal to black or white background. 

I haven't conducted many experiments on this and I guess using a smaller learning rate for background will be better.

Zehao

**Comment by weijielyu** [comment]
I see. Thanks for your explanation!
