### ISSUE TITLE
Question for Replicating Table 4

### ISSUE THREAD

**Issue by jk4011** [VITA-Group/FSGS#24]
<p>Hello, and thank you for your insightful research. I am intrigued by the results in your paper and am attempting to replicate them, particularly for the ablation results corresponding to Table 4.</p>
<p>In my replication, I noticed a discrepancy in the results; the PSNR value I obtained after removing three components is 19.78, which differs from what is reported in Table 4. Could you please clarify if there are other factors, possibly not detailed in the paper, that might have contributed to this performance improvement?</p>
<p>Additionally, I observed in your code the use of concepts like confidence, which is different from the vanilla 3DGS. Are these variations explicitly mentioned in the paper?</p>

  | Paper | Replication at 10k
-- | -- | --
w/o unpooling, guidance, pseudo | 17.83 | 19.39
w/o guidance, pseudo | 18.64 | -
w/o pseudo | 19.93 | 19.79
FSGS | 20.43 | 20.52

**Comment by zehaozhu** [comment]
Hi, thanks for your interest in our work.

When removing three components, it becomes equivalent to the vanila 3DGS. So we use vanilla 3DGS code for test and initialize the model with dense point cloud from colmap. We might release the related checkpoint in the future.

The confidence argument is a advance feature which we do not use in this paper. The basic idea is that each Gaussian is assigned with a distinct learning rate based on its confidence.
