### ISSUE TITLE
submodules/diff-gaussian-rasterization-confidence      submodules/simple-knn会出现错误？

### ISSUE THREAD

**Issue by luxiffa** [VITA-Group/FSGS#26]
你好，为什么安装 
submodules/diff-gaussian-rasterization-confidence
submodules/simple-knn会出现错误？
想知道问题出在哪里？
`
Processing e:\fsgs\submodules\simple-knn
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: simple-knn
  Building wheel for simple-knn (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [63 lines of output]
      running bdist_wheel
      E:\envs\3dgs\lib\site-packages\torch\utils\cpp_extension.py:476: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
        warnings.warn(msg.format('we could not find ninja.'))
      running build
      running build_ext
      E:\envs\3dgs\lib\site-packages\torch\utils\cpp_extension.py:359: UserWarning: Error checking compiler version for cl: [WinError 2] 系统找不到指定的文件。
        warnings.warn(f'Error checking compiler version for {compiler}: {error}')
      building 'simple_knn._C' extension
      creating build
      creating build\temp.win-amd64-cpython-39
      creating build\temp.win-amd64-cpython-39\Release
      "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\bin\HostX86\x64\cl.exe" /
c /nologo /O2 /W3 /GL /DNDEBUG /MD -IE:\envs\3dgs\lib\site-packages\torch\include -IE:\envs\3dgs\lib\site-packages
\torch\include\torch\csrc\api\include -IE:\envs\3dgs\lib\site-packages\torch\include\TH -IE:\envs\3dgs\lib\site-pa
ckages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\include" -IE:\envs\3dgs\inclu
de -IE:\envs\3dgs\Include "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\inc
lude" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\ATLMFC\include" "-IC:\P
rogram Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kit
s\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um" "-IC:\Program
 Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.
0.22621.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt" "-IC:\Program Files (
x86)\Windows Kits\NETFXSDK\4.8\include\um" /EHsc /Tpext.cpp /Fobuild\temp.win-amd64-cpython-39\Release\ext.obj /MD
 /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /EHsc /wd4624 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0
      ext.cpp
      E:\envs\3dgs\lib\site-packages\torch\include\c10/macros/Macros.h(138): warning C4067: 预处理器指令后有意外标 - 应输入换行符
      "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\bin\nvcc" -c simple_knn.cu -o build\temp.win-amd64
-cpython-39\Release\simple_knn.obj -IE:\envs\3dgs\lib\site-packages\torch\include -IE:\envs\3dgs\lib\site-packages
\torch\include\torch\csrc\api\include -IE:\envs\3dgs\lib\site-packages\torch\include\TH -IE:\envs\3dgs\lib\site-pa
ckages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\include" -IE:\envs\3dgs\inclu
de -IE:\envs\3dgs\Include "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\inc
lude" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\ATLMFC\include" "-IC:\P
rogram Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kit
s\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um" "-IC:\Program
 Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.
0.22621.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt" "-IC:\Program Files (
x86)\Windows Kits\NETFXSDK\4.8\include\um" -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -Xcud
afe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=field_without_dll_interface -Xcud
afe --diag_suppress=base_class_has_different_dll_interface -Xcompiler /EHsc -Xcompiler /wd4190 -Xcompiler /wd4018 
-Xcompiler /wd4275 -Xcompiler /wd4267 -Xcompiler /wd4244 -Xcompiler /wd4251 -Xcompiler /wd4819 -Xcompiler /MD -D__
CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERA
TORS__ --expt-relaxed-constexpr -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_61,code=compute_61 -gencode=arch=compute_61,code=sm_61 --use-local-env
      simple_knn.cu(23): warning C4005: “__CUDACC__”: 宏重定义
      simple_knn.cu(23): note: 之前在命令行上声明的“__CUDACC__”
      simple_knn.cu(23): warning C4005: “__CUDACC__”: 宏重定义
      simple_knn.cu(23): note: 之前在命令行上声明的“__CUDACC__”
      C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\include\cuda\std\detail\libcxx\include\support\atomic\atomic_msvc.h(15): warning C4005: “_Compiler_barrier”: 宏重定义
      C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.38.33130/include\xatomic.h(55): note: 参见“_Compiler_barrier”的前一个定义
      E:\FSGS\submodules\simple-knn\simple_knn.h(18): error: identifier "int32_t" is undefined

      C:/Program Files (x86)/Windows Kits/10//include/10.0.22621.0//um\winnt.h(24437): warning #174-D: expression has no effect

      C:/Program Files (x86)/Windows Kits/10//include/10.0.22621.0//um\winuser.h(14668): warning #108-D: signed bit field of length 1

      C:/Program Files (x86)/Windows Kits/10//include/10.0.22621.0//um\winuser.h(14669): warning #108-D: signed bit field of length 1

      C:/Program Files (x86)/Windows Kits/10//include/10.0.22621.0//um\wincrypt.h(21836): warning #1835-D: attribute "dllimport" does not apply here

      C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcndr.h(730): warning #108-D: signed bit field of length 1

      C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcndr.h(731): warning #108-D: signed bit field of length 1

      C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcndr.h(732): warning #108-D: signed bit field of length 1

      C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcndr.h(733): warning #108-D: signed bit field of length 1

      C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcndr.h(734): warning #108-D: signed bit field of length 1

      C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcndr.h(735): warning #108-D: signed bit field of length 1

      C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcndr.h(736): warning #108-D: signed bit field of length 1

      C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcndr.h(737): warning #108-D: signed bit field of length 1

      C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcndr.h(738): warning #108-D: signed bit field of length 1

      C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcndr.h(739): warning #108-D: signed bit field of length 1

      C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcndr.h(740): warning #108-D: signed bit field of length 1

      C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcndr.h(741): warning #108-D: signed bit field of length 1

      C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcndr.h(742): warning #108-D: signed bit field of length 1

      simple_knn.cu(192): error: declaration is incompatible with "void SimpleKNN::knn(int, float3 *, float *, <error-type> *)"
  ERROR: Failed building wheel for simple-knn
  Running setup.py clean for simple-knn
Failed to build simple-knn
ERROR: Could not build wheels for simple-knn, which is required to install pyproject.toml-based projects

`

**Comment by zehaozhu** [comment]
I only test my code on Ubuntu18.04. Maybe you can compile it on a ubuntu machine?
