### ISSUE TITLE
Question about the function to generate random poses

### ISSUE THREAD

**Issue by yinlily12** [VITA-Group/FSGS#34]
Hi,

I am interested in your fancy work. I have one question about the function `generate_random_poses_llff` and `generate_random_poses_llff` to generate random poses. I am curious to know which algorithm is related to this?

Could you please provide some insights or details about the algorithm used in the generation of random pose? I would greatly appreciate any information you can share.

I am looking forward to hearing back from you. Thank you very much.

Best

**Comment by PatD123** [comment]
Hey @yinlily
I'm trying to recreate the llff following the instructions on the readme for this repo. However, I'm getting issues with decoding the images.bin file because the images.txt file specified in the colmap_lff doesn't exist. How did you fix this?

**Comment by Toothable** [comment]
Hi, I am also confused that It seems that the generation of pseudo poses is the average of all training view poses with noise. However, the description in Page 4 of this paper is "The synthesized view is sampled from the two closest training views in Euclidean space, calculating the averaged camera orientation and interpolating a virtual one between them."

**Comment by yinlily12** [comment]
Hey @PatD123 , I tried `colmap model_converter \
    --input_path path-to-binary-reconstruction \
    --output_path path-to-txt-reconstruction \
    --output_type TXT` (https://github.com/colmap/colmap/issues/697) to transfer the bin file to the text file.

**Comment by zehaozhu** [comment]
Hi @yinlily12 , thanks for your interest in our work.

This algorithm is borrowed from https://github.com/google-research/multinerf/blob/main/internal/camera_utils.py#L159. We generate forward/360degree views based on known training views
