### ISSUE TITLE
Question for Reproduce Experimental Results

### ISSUE THREAD

**Issue by Riser6** [VITA-Group/FSGS#35]
Hello, and thank you for your insightful research. I am intrigued by the results in your paper and am attempting to replicate them. 
I followed the instructions in your document to conduct the reproduction experiment on LLFF dataset and directly used the proprecessed sparse and dense point cloud which provided by you. The PSNR value (18.38 and 18.31, I conduct the replication experiment twice) are significantly lower than what is reported in your paper(20.43).  Metrics for all scan in two replication experiments are provided in the attachmen
[reproduce.txt](https://github.com/VITA-Group/FSGS/files/14375929/reproduce.txt)
t.

May I ask if you know the possible reasons for this? Additionally, according to the default settings in the code you provided, the image resolution is 504 × 378, which is different from the resolution reported in the Table 1(503 × 381). I don’t know if there is some misalignment.

I would be very grateful if you could clarify my confusion. Thank you again for contributing such insightful work to the community.

**Comment by ckjCEO** [comment]
> Hello, and thank you for your insightful research. I am intrigued by the results in your paper and am attempting to replicate them. I followed the instructions in your document to conduct the reproduction experiment on LLFF dataset and directly used the proprecessed sparse and dense point cloud which provided by you. The PSNR value (18.38 and 18.31, I conduct the replication experiment twice) are significantly lower than what is reported in your paper(20.43). Metrics for all scan in two replication experiments are provided in the attachmen [reproduce.txt](https://github.com/VITA-Group/FSGS/files/14375929/reproduce.txt) t.
> 
> May I ask if you know the possible reasons for this? Additionally, according to the default settings in the code you provided, the image resolution is 504 × 378, which is different from the resolution reported in the Table 1(503 × 381). I don’t know if there is some misalignment.
> 
> I would be very grateful if you could clarify my confusion. Thank you again for contributing such insightful work to the community.

请问你是直接用的作者提供的dense点云还是自己重新用colmap建的？不同质量点云重建效果差别还是很大的

**Comment by Riser6** [comment]
I did directly use the dense point cloud provided by you. And I find the perfomance gap is due to I use the command "python render.py --source_path dataset/nerf_llff_data/horns/  --model_path  output/horns --iteration 10000  --video  --fps 30" instead of using the command "python render.py --source_path dataset/nerf_llff_data/horns/  --model_path  output/horns --iteration 10000". After rendering the video, rendering images again seems to result in lower quality. And after swapping the order of rendering images and rendering videos in the render_sets fuction of render.py, the test metrics for both test commands are the same. So, I suspect whether during the testing phase, some parameters of the 3DGS model are still being updated.

**Comment by zehaozhu** [comment]
Hi @ckjCEO , thanks for your interest in our work.

Colmap receives **only the sparse training images** as input.  We filter the sparse training views for colmap input at [here](https://github.com/VITA-Group/FSGS/blob/main/tools/colmap_llff.py#L164). 

Executing this script should produce similar results to the point cloud we provided. If you meet any problem in point cloud reconstruction, please don't hesitate to contact me.

**Comment by zehaozhu** [comment]
Hi @Riser6, thanks for your interest in our work.

I believe we are not updating the parameters of 3DGS for video rendering. However, we do update the camera view at [here](https://github.com/VITA-Group/FSGS/blob/main/render.py#L71). So the solution is to use deep copy at [here](https://github.com/VITA-Group/FSGS/blob/main/render.py#L57).

**Comment by Riser6** [comment]
> Hi @Riser6, thanks for your interest in our work.
> 
> I believe we are not updating the parameters of 3DGS for video rendering. However, we do update the camera view at [here](https://github.com/VITA-Group/FSGS/blob/main/render.py#L71). So the solution is to use deep copy at [here](https://github.com/VITA-Group/FSGS/blob/main/render.py#L57).

Thanks for your patient reply, it did solve my problem.

**Comment by heandrea** [comment]
> > 您好，感谢您对我们的工作感兴趣。
> > 我相信我们不会更新用于视频渲染的 3DGS 参数。但是，我们确实[在此处](https://github.com/VITA-Group/FSGS/blob/main/render.py#L71)更新了摄像机视图。所以解决方案是在这里使用 deep [copy。](https://github.com/VITA-Group/FSGS/blob/main/render.py#L57)
> 
> 感谢您的耐心回复，它确实解决了我的问题。

Hello,I meet the same issue.The PSNR(19.42) are  lower than the paper(20.31).How to solve it?Thanks for your reply.
