### ISSUE TITLE
point3d.ply

### ISSUE THREAD

**Issue by whalien-902** [VITA-Group/FSGS#4]
Could you please provide the point cloud file after you processed it? Because it cannot be used due to an exception when I installed colmap

**Comment by whalien-902** [comment]
I saw that you carried out colmap dense matching in github, whether you used sparse point cloud or dense point cloud in training

**Comment by whalien-902** [comment]
![image](https://github.com/VITA-Group/FSGS/assets/102122699/8efae7f0-8b57-48fb-a8df-e33895c2f832)
![image](https://github.com/VITA-Group/FSGS/assets/102122699/f5640142-d308-4231-9738-04c4eaba8858)

**Comment by zhiwenfan** [comment]
Hi, 

Thanks for posting this issue.
We highly suggest you to build the docker image which already contains the colmap installation via https://github.com/colmap/colmap, using the given dockerfile.
We use dense fused point cloud.

Bests.

**Comment by zehaozhu** [comment]
Hi @whalien-902 

Thanks for your interest in our work. We have released both the sparse and dense point cloud for mipnerf360 and LLFF dataset [in this link](https://drive.google.com/drive/folders/1lYqZLuowc84Dg1cyb8ey3_Kb-wvPjDHA?usp=sharing). We use dense point cloud during training.

Zehao
