### ISSUE TITLE
The function“proximity” is commented out in the code？

### ISSUE THREAD

**Issue by zsz-pro** [VITA-Group/FSGS#5]
Nice work！ But I got a question.
Why is the “Proximity-guided Gaussian Unpooling” mentioned in the paper commented out in the code?
![image](https://github.com/VITA-Group/FSGS/assets/61933660/6c0aa32d-a5a6-4ea9-9ef8-4b356f13d5e1)

**Comment by zehaozhu** [comment]
Hi, thanks for your interest in our work. The project is not finished yet. We will update this function in the future.
