### ISSUE TITLE
cannot install submodule/simple-knn

### ISSUE THREAD

**Issue by Gurutva** [VITA-Group/FSGS#53]
FYI : I referred this feed https://github.com/graphdeco-inria/gaussian-splatting/issues/332 to make an environment , since it worked for me for original gaussian-splatting repo. 
 
    git clone https://github.com/VITA-Group/FSGS --recursive
    conda create -n FSGS python=3.7
    conda activate FSGS
    conda install pytorch==1.13.1 torchvision==0.14.1 torchaudio==0.13.1 pytorch-cuda=11.7 -c pytorch -c nvidia
    pip install submodules/diff-gaussian-rasterization-confidence
    pip install submodules/simple-knn
    pip install matplotlib==3.5.3 torchmetrics==1.2.0 timm==0.9.12 opencv_python==4.8.1.78 imageio==2.31.2 open3d==0.17.0

Don't know the reason but 

     conda env create --file environment.yml 
always breaks for me

Getting the below error when running 

     pip install submodules/simple-knn
.. error =>

     2 errors detected in the compilation of "simple_knn.cu".
          simple_knn.cu
          error: command 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.7\\bin\\nvcc.exe' failed with exit code 2
          [end of output]
    
      note: This error originates from a subprocess, and is likely not a problem with pip.
    error: legacy-install-failure
    
    × Encountered error while trying to install package.
    ╰─> simple-knn
    
    note: This is an issue with the package mentioned above, not pip.
    hint: See above for output from the failure.

=====================================================

Another try with the FSGS environment.yml configurations. 

      git clone https://github.com/VITA-Group/FSGS --recursive
      conda create -n FSGS2 python=3.8.1
      conda activate FSGS2
      conda install pytorch==1.12.1 torchvision==0.13.1 torchaudio==0.12.1 pytorch-cuda=11.6 -c pytorch -c nvidia
      pip install submodules/diff-gaussian-rasterization-confidence
      pip install submodules/simple-knn
      pip install matplotlib==3.5.3 torchmetrics==1.2.0 timm==0.9.12 opencv_python==4.8.1.78 imageio==2.31.2 open3d==0.17.0

Getting the below error when running 

     pip install submodules/simple-knn
.. error =>

    File "C:\Users\USER\anaconda3\envs\FSGS2\lib\site-packages\torch\utils\cpp_extension.py", line 1487, in _write_ninja_file_and_compile_objects
              _run_ninja_build(
            File "C:\Users\USER\anaconda3\envs\FSGS2\lib\site-packages\torch\utils\cpp_extension.py", line 1824, in _run_ninja_build
              raise RuntimeError(message) from e
          RuntimeError: Error compiling objects for extension
          [end of output]
    
      note: This error originates from a subprocess, and is likely not a problem with pip.
      ERROR: Failed building wheel for simple_knn
      Running setup.py clean for simple_knn
    Failed to build simple_knn
    ERROR: Could not build wheels for simple_knn, which is required to install pyproject.toml-based projects

**Comment by Gurutva** [comment]
issue got resolved. Thanks.

**Comment by atharvagasheTAMU** [comment]
Can you please tell how did you resolve this issue?
