### ISSUE TITLE
TypeError: <lambda>() got an unexpected keyword argument 'confidence'

### ISSUE THREAD

**Issue by 123456xuan** [VITA-Group/FSGS#57]
Hello, I have the following problem, and I have installed all the required environments and corresponding versions, but there are still errors. Could you please help me solve it? Thank you

Traceback (most recent call last):
  File "/home/root/FSGS/train.py", line 279, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args)
  File "/home/root/FSGS/train.py", line 90, in training
    render_pkg = render(viewpoint_cam, gaussians, pipe, background)
  File "/home/root/FSGS/gaussian_renderer/__init__.py", line 43, in render
    raster_settings = GaussianRasterizationSettings(
TypeError: <lambda>() got an unexpected keyword argument 'confidence'
Training progress:   0%|

**Comment by JakeXin7** [comment]
Hi, I met the same problem. Have you solved it ?
