### ISSUE TITLE
Urgent Request for Update on proximity Component in gaussian_model Module

### ISSUE THREAD

**Issue by UranusITS** [VITA-Group/FSGS#8]
Thank you for your great work!

I am writing to inquire about the upcoming update for the `proximity` component within the `gaussian_model` module mentioned in #5 . My team and I are currently conducting research that heavily relies on this particular feature, and we are eager to compare our experimental methods with yours.

Could you please provide an estimated timeline for when this update might be available? Understanding your schedule will greatly assist us in planning our research. If the update is expected to take a considerable amount of time, we might need to proceed with implementing this component ourselves.

Thank you for your attention to this matter.

**Comment by ZhangCYG** [comment]
same issue

**Comment by chensjtu** [comment]
waiting update

**Comment by zehaozhu** [comment]
Hi @chensjtu @ZhangCYG @UranusITS 

Sorry for the late update. I have now updated the proximity module. You may need recompile the simple-knn submodule to run it. Thank you!
